fixiksite/urls.py
from django.contrib import admin
from django.urls import path, include
from fixiksite.settings import DEBUG


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls', namespace='mysite')),
    path('catalog/', include('services.urls', namespace='services'))
    # path('', TemplateView.as_view(template_name='startpage.html'), name='home')
] 

if DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        ]

mysite/urls.py
from django.urls import path
from .views import *

app_name = 'mysite'

urlpatterns = [
path('', startpage, name='start-page'),
path('login/', loginpage, name='login-page'),
path('registration/', registration, name='regs-page')
]

services/urls.py
from django.urls import path
from .views import *

app_name = 'services'

urlpatterns = [
path('', catalog, name='catalog-page'),
path('test/', tests, name='test-page')
]

mysite/models.py
from django.db import models

services/models.py
from django.db import models


# Create your models here.
class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    
    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию услуг'
        verbose_name_plural = 'Категории услуг'
    
    def __str__(self):
        return self.name
    
       
        
        
class Services(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    tarifexternalname = models.CharField(max_length=150, unique=True, blank=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    category = models.ForeignKey(to=Categories, on_delete=models.PROTECT, verbose_name='Категория услуг')
    
    class Meta:
        db_table = 'service'
        verbose_name = 'Услугу'
        verbose_name_plural = 'Услуги'
        
    def __str__(self):
        return self.name

mysite/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound
from django.views.generic import ListView
from django.urls import path

from services.models import Categories

# Create your views here.


def startpage(request):
    
    # categories = Categories.objects.all()
    
    context = {
        'title': 'Главная страница',
        # 'categories':categories,
    }
    return render(request, 'mysite/startpage.html', context=context)


def loginpage(request):
    context = {
        'title': 'Страница авторизации'
    }
    return render(request, 'mysite/loginpage.html', context=context)

def registration(request):
    context = {
        'title': 'Страница регистрации'
    }
    return render(request, 'mysite/registrationpage.html', context=context)

def pageNotFound(requsest, exception):
    return HttpResponseNotFound('<h1> Страница не найдена </h1>')

services/views.py
from django.shortcuts import render

from services.models import Services
from services.models import Categories
# Create your views here.


def catalog(request):
    
    # services = Services.objects.all()
    # categories = Categories.objects.all()
    
    
    context = {
        'title':'Домашний интернет',
        # 'services':services,
        # 'categories': categories,
        
    }
    return render(request, 'services/catalog.html', context=context)





def tests(request):
    
    categories = Categories.objects.all()
    
    context = {
        'title':'тестовая страница',
        'categories': categories,
       
    }
    return render(request, 'services/test.html', context=context)

mysite/templates/mysite/base.html
{% load static %}
{% load service_tags %}

<!DOCTYPE html>
<html lang='ru'>

    <head>
        {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" /> {% endcomment %}
        <link rel="icon" type="image/x-icon" href= "{% static 'mysite/images/hive_logo.svg' %}"/>
        
        <meta charset='UTF-8'>
        <meta name='viewpoint' content='width=device-width, initial=scale=1.0'>
        <title>{{ title }}</title>



        {% block css %} {% endblock %}
    
    </head>

    <body>
        
        <aside>
            <img src = "{% static 'mysite/images/hive_logo.svg' %}">
            <span class="logo">fixiK</span>
            <h3>Навигация по сайту</h3>
            <ul>
                <a href="{%url 'mysite:start-page' %}" style="text-decoration: none;"> <li> <i class="fa-solid fa-house-user" style="color: #ffffff;"></i> Главная страница</li></a>
                <a href="{%url 'mysite:login-page' %}" style="text-decoration: none;"> <li> <i class="fa-solid fa-address-card fa-sm" style="color: #ffffff;"></i> Личный кабинет </li></a>
                
                {% tag_categories as categories %}
                {% for category in categories %}
                    <a href="{%url 'services:catalog-page' %}" style="text-decoration: none;"> <li> <i class="fa-solid fa-globe" style="color: #ffffff;"></i> {{ category.name }} </li></a>
                {% endfor %}
                    
                <a href="" style="text-decoration: none;"> <li> <i class="fa-solid fa-circle-info" style="color: #ffffff;"></i> О нас </li></a>
                <a href="{%url 'services:test-page' %}" style="text-decoration: none;"> <li> <i class="fa-solid fa-headset" style="color: #ffffff;"></i> Поддержка </li></a>
            </ul> 
        </aside>


        {% block content %} {% endblock %}
        {% block scripts %} {% endblock %}

    </body>
</html>

mysite/templates/mysite/loginpage.html
{% comment %} {% extends 'mysite/base.html' %} {% endcomment %}
{% load static %}

<head>
    <title>{{ title }}</title>
</head>


{%block css %}

<link rel="stylesheet" href="{% static 'mysite/css/login_page.css' %}">

{%endblock%}



{% block content %}

    <div class="main">
        <a href="{%url 'mysite:start-page' %}" style="text-decoration: none;"><img src = "{% static 'mysite/images/hive_logo.svg' %}">
        <span class="logo">fixiK</span></a>
        <h3>Авторизация</h3>
        <form action="">

            <input type="text"
                   id="login"
                   name="login"
                   placeholder="Введите ваш логин" required>

            <input type="password"
                   id="password"
                   name="password"
                   placeholder="Введите ваш пароль" required>

            <div class="wrap">
                <button type="submit">Войти</button>
            </div>
        </form>
        
        <p><li><a href="{% url 'mysite:regs-page' %}" style="text-decoration: none;">
                Создать аккаунт
            </a></li>
        </p>
    </div>

{% endblock %}

mysite/templates/mysite/registrationpage.html
{% comment %} {% extends 'mysite/base.html' %} {% endcomment %}
{% load static %}


<head>
    <title>{{ title }}</title>
</head>


{% block css %} 

<link rel="stylesheet" href="{% static 'mysite/css/registration_page.css' %}">

{% endblock %}



{% block content %}

		<div class="main">
			<a href="{%url 'mysite:start-page' %}" style="text-decoration: none;"><img src = "{% static 'mysite/images/hive_logo.svg' %}">
			<span class="logo">fixiK</span></a>
			<h3>Регистрация</h3>
			<form action="">
				
				<input type="text"
					   id="name"
					   name="firstname"
					   placeholder="Имя" required>

				
				<input type="text"
					   id="lastname"
					   name="lastname"
					   placeholder="Фамилия" required>


				<input type="text"
					   id="mobile"
					   name="mobile"
					   maxlength="10"
					   placeholder="Номер телефона" required>


				<input type="email"
					   id="email"
					   name="email"
					   placeholder="Email" required>


				<input type="text"
						id="login"
						name="login"
						placeholder="Логин" required>


				<input type="password"
					   id="password"
					   name="password"
					   pattern="^(?=.*\d)(?=.*[a-zA-Z])(?=.*[^a-zA-Z0-9])\S{8,}$"
					   title="Пароль должен содержать как минимум одну цифру, одну букву алфавита, один символ и быть длиной не менее 8 символов."
					   placeholder="Пароль" required>

				<input type="password"
					   id="repassword"
					   name="repassword"
					   placeholder="Повторите пароль" required>

				
				<div class="wrap">
					<button type="submit">
						Создать аккаунт
					</button>
				</div>
		</div>

{% endblock %}

mysite/templates/mysite/startpage.html
{% extends 'mysite/base.html' %}
{% load static %}
{% load service_tags %}


{% block css %} 
    
    {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'mysite/css/start_page.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.6.0/css/fontawesome.min.css" integrity="sha384-NvKbDTEnL+A8F/AA5Tc5kmMLSJHUO868P+lDtTpJIeQdGYaUIuLr4lVGOEA1OcMy" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'mysite/css/awesome/css/all.css' %}">

{% endblock %}


{% block content %}

{% endblock %}

services/templates/services/catalog.html
{% extends 'mysite/base.html' %}
{% load static %}
{% load service_tags %}

{% block css %} 

    <link rel="stylesheet" href="{% static 'services/css/catalog_page.css' %}">

    {% comment %} <link rel="stylesheet" href="https://cdn.j.sdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'mysite/css/start_page.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.6.0/css/fontawesome.min.css" integrity="sha384-NvKbDTEnL+A8F/AA5Tc5kmMLSJHUO868P+lDtTpJIeQdGYaUIuLr4lVGOEA1OcMy" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'mysite/css/awesome/css/all.css' %}">

{% endblock %}


{% block content %} 


   <!--Модальное окно-->
   <div class="modal" id="modal">

    <div class="modal-content" id="modal-content">
        <div class="modal-close" id="modal-close">&#10006</div>

        <h3>Заявка на подключение</h3>

        <form id="requestForm" action="">
            <input type="text" id='firstName' placeholder='Имя'>
            <input type="text" id='lastName' placeholder='Фамилия'>
            <input type="text" id='mobile' placeholder='Номер телефона'>
            <input type="text" id='address' placeholder='Адрес'>
                
            <button type="submit">Оставить заявку</button>
        </form>

            
    </div>
</div>


<!-- Тарифные планы-->
<div class='container'>

    <h1 class='heading'> Выбери свой тариф </h1>

    <div class = 'box-container'>
        
        <!-- Отсылка к DOOM'у :) -->

        {% tag_services as services %}
        {% for service in services %}

            <div class="box">
                <img src="{% static 'services/images/home-internet.jpg' %}" alt=''>
                <h3> {{ service.name }} </h3>
                <p> {{ service.description }} </p>
                <button class="button" tarifnumber="{{service.tarifexternalname}}" id="button{{forloop.counter}}"> Подключить </button>
            </div>
    
        {% endfor %}
            
    </div> 
</div>


{% endblock %}

{% block scripts %} 
    
    <script src="{% static 'services/js/main.js' %}" async defer></script>

{% endblock %}

        

services/templates/services/test.html
{% extends 'mysite/base.html' %}
{% load static %}
{% load service_tags %}


{% block css %} 

    <link rel="stylesheet" href="{% static 'services/css/catalog_page.css' %}">

    {% comment %} <link rel="stylesheet" href="https://cdn.j.sdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'mysite/css/start_page.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.6.0/css/fontawesome.min.css" integrity="sha384-NvKbDTEnL+A8F/AA5Tc5kmMLSJHUO868P+lDtTpJIeQdGYaUIuLr4lVGOEA1OcMy" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'mysite/css/awesome/css/all.css' %}">

{% endblock %}


{% block content %} 



{% endblock %}

{% block scripts %} 
    
    <script src="{% static 'services/js/main.js' %}" async defer></script>

{% endblock %}

        